-- ================================================================
-- DEPRECATED: This file is no longer maintained.
-- ================================================================
--
-- Please use COMPLETE_DATABASE_SETUP.sql instead.
-- It contains the full, up-to-date schema including:
--   - All table definitions with image/video columns
--   - Row Level Security (RLS) policies
--   - Safe migration ALTER TABLE statements
--   - Seed data with placeholder images (Unsplash CDN)
--   - Storage bucket setup
--   - Contact submissions table
--   - Homepage sections configuration
--
-- Alternatively, SUPABASE_SCHEMA.sql provides a lighter version
-- with tables, basic RLS, and seed data (no migrations/storage).
--
-- ================================================================
-- To set up your database, run in the Supabase SQL Editor:
--
--   COMPLETE_DATABASE_SETUP.sql   (recommended, full setup)
--   SUPABASE_SCHEMA.sql           (lighter alternative)
--
-- ================================================================
